/**
 * TypeScript interfaces matching the WIT types generated by jco transpile.
 * These mirror the shapes in wit/types.wit as they appear after jco
 * conversion (camelCase, result → throw, option → undefined).
 */

export type HostError =
  | "permission-denied"
  | "not-found"
  | "invalid-input"
  | "network-error"
  | "rate-limited"
  | "domain-not-allowed"
  | "internal";

export interface AccountInfo {
  id: string;
  fullName: string;
  accountType: string;
  isPostable: boolean;
}

export interface QueryParams {
  limit: number;
  offset: number;
  accountFilter: string;
  fromDate: string;
  toDate: string;
}

export interface Money {
  amount: string;
  currency: string;
}

export interface Posting {
  account: string;
  amount: Money;
}

export interface Transaction {
  date: string;
  description: string;
  postings: Posting[];
  metadata: [string, string][];
}

export interface CurrencyBalance {
  currency: string;
  amount: string;
}

export interface ConfigField {
  key: string;
  label: string;
  fieldType: string;
  required: boolean;
  defaultValue: string;
  description: string;
  options: string;
}

export interface PluginMetadata {
  name: string;
  version: string;
  description: string;
  author: string;
}

export interface PricePoint {
  date: string;
  fromCurrency: string;
  toCurrency: string;
  rate: string;
  source: string;
}

export interface SyncState {
  cursor: string;
}

export interface SyncResult {
  transactions: Transaction[];
  prices: PricePoint[];
  newState: SyncState;
  summary: string;
}

export interface HttpRequest {
  method: string;
  url: string;
  headers: [string, string][];
  body: Uint8Array;
}

export interface HttpResponse {
  status: number;
  headers: [string, string][];
  body: Uint8Array;
}

/** Import object interface that jco expects for handler plugins. */
export interface HandlerImports {
  "dledger:plugin/ledger-read": LedgerReadImports;
  "dledger:plugin/logging": LoggingImports;
  "dledger:plugin/plugin-storage": PluginStorageImports;
  "dledger:plugin/types": Record<string, never>;
  "wasi:cli/environment": WasiEnvironmentImports;
  "wasi:cli/exit": WasiExitImports;
  "wasi:cli/stderr": WasiStderrImports;
  "wasi:io/error": WasiIoErrorImports;
  "wasi:io/streams": WasiIoStreamsImports;
}

/** Import object interface that jco expects for source plugins. */
export interface SourceImports {
  "dledger:plugin/ledger-write": LedgerWriteImports;
  "dledger:plugin/logging": LoggingImports;
  "dledger:plugin/plugin-storage": PluginStorageImports;
  "dledger:plugin/types": Record<string, never>;
  "dledger:plugin/ledger-read"?: LedgerReadImports;
  "dledger:plugin/http-client"?: HttpClientImports;
  "wasi:cli/environment": WasiEnvironmentImports;
  "wasi:cli/exit": WasiExitImports;
  "wasi:cli/stderr": WasiStderrImports;
  "wasi:io/error": WasiIoErrorImports;
  "wasi:io/streams": WasiIoStreamsImports;
}

/**
 * Exports from instantiated handler plugins.
 * All exports are synchronous (no JSPI) since handler plugins don't use HTTP.
 */
export interface HandlerExports {
  handlerOps: {
    configSchema(): ConfigField[];
    configure(config: [string, string][]): void;
    process(params: string): string;
    generateReport(format: string, params: string): Uint8Array;
  };
  metadata: {
    getMetadata(): PluginMetadata;
  };
}

/**
 * Exports from instantiated source plugins.
 * All exports are synchronous — HTTP uses sync XMLHttpRequest, not JSPI.
 */
export interface SourceExports {
  sourceOps: {
    configSchema(): ConfigField[];
    configure(config: [string, string][]): void;
    testConnection(): string;
    sync(state: SyncState): SyncResult;
    fullImport(state: SyncState): SyncResult;
  };
  metadata: {
    getMetadata(): PluginMetadata;
  };
}

export interface HttpClientImports {
  send(request: HttpRequest): HttpResponse;
}

export interface LedgerWriteImports {
  submitTransactions(transactions: Transaction[]): number;
  submitPrices(prices: PricePoint[]): number;
  ensureAccount(fullName: string, accountType: string): string;
}

export interface LedgerReadImports {
  listAccounts(): AccountInfo[];
  getAccount(id: string): AccountInfo | undefined;
  queryTransactions(params: QueryParams): Transaction[];
  getBalance(accountId: string, asOf: string): CurrencyBalance[];
  getBalanceWithChildren(accountId: string, asOf: string): CurrencyBalance[];
  getExchangeRate(fromCurrency: string, toCurrency: string, date: string): string | undefined;
}

export interface LoggingImports {
  debug(message: string): void;
  info(message: string): void;
  warn(message: string): void;
  error(message: string): void;
}

export interface PluginStorageImports {
  get(key: string): string | undefined;
  set(key: string, value: string): void;
  delete(key: string): void;
  listKeys(): string[];
}

// WASI shim interfaces (provided by @bytecodealliance/preview2-shim)
export interface WasiEnvironmentImports {
  getEnvironment(): [string, string][];
}

export interface WasiExitImports {
  exit(status: { tag: string; val?: number }): void;
}

export interface WasiStderrImports {
  getStderr(): unknown;
}

export interface WasiIoErrorImports {
  Error: unknown;
}

export interface WasiIoStreamsImports {
  InputStream: unknown;
  OutputStream: unknown;
}
