use std::collections::BTreeMap;

use crate::formatters::Formatter;
use crate::model::{EntryStatus, SampleData};

pub struct BeancountFormatter;

impl Formatter for BeancountFormatter {
    fn format(&self, data: &SampleData, seed: u64) -> String {
        let mut out = String::new();

        // Header comment
        out.push_str(&format!(
            "; Generated by dsample (seed: {}, entries: {})\n",
            seed,
            data.entries.len()
        ));

        // Operating currency (use first commodity if available)
        if let Some(commodity) = data.commodities.first() {
            out.push_str(&format!(
                "option \"operating_currency\" \"{}\"\n",
                commodity.code
            ));
        }
        out.push('\n');

        // Collect all unique accounts with their earliest date
        let mut account_dates: BTreeMap<String, chrono::NaiveDate> = BTreeMap::new();
        for entry in &data.entries {
            for posting in &entry.postings {
                let beancount_account = posting.account.replace(' ', "-");
                account_dates
                    .entry(beancount_account)
                    .and_modify(|d| {
                        if entry.date < *d {
                            *d = entry.date;
                        }
                    })
                    .or_insert(entry.date);
            }
        }

        // Open directives sorted by account name (BTreeMap is already sorted)
        for (account, date) in &account_dates {
            out.push_str(&format!("{} open {}\n", date.format("%Y-%m-%d"), account));
        }
        if !account_dates.is_empty() {
            out.push('\n');
        }

        // Entries
        for entry in &data.entries {
            let status_marker = match entry.status {
                EntryStatus::Confirmed => "*",
                EntryStatus::Pending => "!",
            };
            out.push_str(&format!(
                "{} {} \"{}\"\n",
                entry.date.format("%Y-%m-%d"),
                status_marker,
                entry.description,
            ));
            for posting in &entry.postings {
                let beancount_account = posting.account.replace(' ', "-");
                out.push_str(&format!(
                    "  {}  {} {}\n",
                    beancount_account, posting.amount, posting.currency,
                ));
            }
            out.push('\n');
        }

        // Price directives
        for price in &data.prices {
            out.push_str(&format!(
                "{} price {} {} {}\n",
                price.date.format("%Y-%m-%d"),
                price.commodity,
                price.price,
                price.target_currency,
            ));
        }

        out
    }
}
