use std::collections::BTreeSet;

use crate::formatters::Formatter;
use crate::model::{EntryStatus, SampleData};

pub struct HledgerFormatter;

impl Formatter for HledgerFormatter {
    fn format(&self, data: &SampleData, seed: u64) -> String {
        let mut out = String::new();

        // Header comment
        out.push_str(&format!(
            "; Generated by dsample (seed: {}, entries: {})\n\n",
            seed,
            data.entries.len()
        ));

        // Account declarations (collect all unique accounts, sorted)
        let mut accounts: BTreeSet<&str> = BTreeSet::new();
        for entry in &data.entries {
            for posting in &entry.postings {
                accounts.insert(&posting.account);
            }
        }
        for account in &accounts {
            out.push_str(&format!("account {}\n", account));
        }
        if !accounts.is_empty() {
            out.push('\n');
        }

        // Commodity declarations
        for commodity in &data.commodities {
            out.push_str(&format!("commodity {}\n", commodity.code));
        }
        if !data.commodities.is_empty() {
            out.push('\n');
        }

        // Entries
        for entry in &data.entries {
            let status_marker = match entry.status {
                EntryStatus::Confirmed => "*",
                EntryStatus::Pending => "!",
            };
            out.push_str(&format!(
                "{} {} {}\n",
                entry.date.format("%Y-%m-%d"),
                status_marker,
                entry.description,
            ));
            if !entry.tags.is_empty() || !entry.links.is_empty() {
                let mut parts: Vec<String> = Vec::new();
                for tag in &entry.tags {
                    parts.push(format!("{tag}:"));
                }
                for link in &entry.links {
                    parts.push(format!("link:{link}"));
                }
                out.push_str(&format!("    ; {}\n", parts.join(", ")));
            }
            for posting in &entry.postings {
                out.push_str(&format!(
                    "  {}  {} {}\n",
                    posting.account, posting.amount, posting.currency,
                ));
            }
            out.push('\n');
        }

        // Price directives
        for price in &data.prices {
            out.push_str(&format!(
                "P {} {} {} {}\n",
                price.date.format("%Y-%m-%d"),
                price.commodity,
                price.price,
                price.target_currency,
            ));
        }

        out
    }
}
