use crate::formatters::Formatter;
use crate::model::{EntryStatus, SampleData};

pub struct LedgerFormatter;

impl Formatter for LedgerFormatter {
    fn format(&self, data: &SampleData, seed: u64) -> String {
        let mut out = String::new();

        // Header comment
        out.push_str(&format!(
            "; Generated by dsample (seed: {}, entries: {})\n\n",
            seed,
            data.entries.len()
        ));

        // Commodity declarations
        for commodity in &data.commodities {
            out.push_str(&format!("commodity {}\n", commodity.code));
        }
        if !data.commodities.is_empty() {
            out.push('\n');
        }

        // Entries
        for entry in &data.entries {
            let status_marker = match entry.status {
                EntryStatus::Confirmed => "*",
                EntryStatus::Pending => "!",
            };
            out.push_str(&format!(
                "{} {} {}\n",
                entry.date.format("%Y-%m-%d"),
                status_marker,
                entry.description,
            ));
            if !entry.tags.is_empty() {
                let joined: Vec<&str> = entry.tags.iter().map(|s| s.as_str()).collect();
                out.push_str(&format!("    ; :{}:\n", joined.join(":")));
            }
            for link in &entry.links {
                out.push_str(&format!("    ; Link: {link}\n"));
            }
            for posting in &entry.postings {
                out.push_str(&format!(
                    "  {}  {} {}\n",
                    posting.account, posting.amount, posting.currency,
                ));
            }
            out.push('\n');
        }

        // Price directives
        for price in &data.prices {
            out.push_str(&format!(
                "P {} {} {} {}\n",
                price.date.format("%Y-%m-%d"),
                price.commodity,
                price.price,
                price.target_currency,
            ));
        }

        out
    }
}
