import type { CsvPreset } from "../../csv-presets/types.js";
import {
  bankStatementPreset,
  krakenLedgerPreset,
  revolutPreset,
  binanceTradePreset,
  coinbaseTransactionsPreset,
  bybitTradePreset,
  bisqPreset,
  bitfinexPreset,
  bitstampPreset,
  bittrexPreset,
  coinlistPreset,
  cryptoComAppPreset,
  cryptoComExchangePreset,
  gateioPreset,
  nexoPreset,
  poloniexPreset,
  yieldAppPreset,
  laBanquePostalePreset,
  n26Preset,
  voletPreset,
} from "../../csv-presets/presets/index.js";

export const builtinCsvPresets: CsvPreset[] = [
  krakenLedgerPreset,
  binanceTradePreset,
  coinbaseTransactionsPreset,
  bybitTradePreset,
  bisqPreset,
  bitfinexPreset,
  bitstampPreset,
  bittrexPreset,
  coinlistPreset,
  cryptoComAppPreset,
  cryptoComExchangePreset,
  gateioPreset,
  nexoPreset,
  poloniexPreset,
  yieldAppPreset,
  laBanquePostalePreset,
  n26Preset,
  voletPreset,
  revolutPreset,
  bankStatementPreset, // lowest priority (score 40-60)
];
