wit_bindgen::generate!({
    world: "handler",
    path: "../../wit",
});

use dledger::plugin::ledger_read;
use dledger::plugin::logging;
use dledger::plugin::plugin_storage;
use dledger::plugin::types::*;

struct ExportHledger;

impl exports::dledger::plugin::metadata::Guest for ExportHledger {
    fn get_metadata() -> PluginMetadata {
        PluginMetadata {
            name: "hledger Export".to_string(),
            version: "0.1.0".to_string(),
            description: "Export ledger to hledger/ledger journal format".to_string(),
            author: "dledger".to_string(),
        }
    }
}

impl exports::dledger::plugin::handler_ops::Guest for ExportHledger {
    fn config_schema() -> Vec<ConfigField> {
        vec![ConfigField {
            key: "base_currency".into(),
            label: "Base Currency".into(),
            field_type: "select".into(),
            required: true,
            default_value: "EUR".into(),
            description: "Base currency for price directives".into(),
            options: "EUR,USD,GBP".into(),
        }]
    }

    fn configure(config: Vec<(String, String)>) -> Result<(), String> {
        for (key, value) in &config {
            plugin_storage::set(key, value)
                .map_err(|e| format!("Storage error: {e:?}"))?;
        }
        Ok(())
    }

    /// Process: return JSON summary of what would be exported.
    fn process(params: String) -> Result<String, String> {
        logging::info("Generating hledger export");

        let (from_date, to_date) = parse_date_range(&params)?;

        let accounts = ledger_read::list_accounts()
            .map_err(|e| format!("Failed to list accounts: {e:?}"))?;

        let mut transactions = ledger_read::query_transactions(&QueryParams {
            limit: 10000,
            offset: 0,
            account_filter: String::new(),
            from_date: from_date.clone(),
            to_date: to_date.clone(),
        })
        .map_err(|e| format!("Failed to query transactions: {e:?}"))?;

        transactions.sort_by(|a, b| a.date.cmp(&b.date));

        Ok(format!(
            "{{\"format\":\"hledger\",\"accounts\":{},\"transactions\":{},\"from_date\":\"{}\",\"to_date\":\"{}\"}}",
            accounts.len(),
            transactions.len(),
            escape_json(&from_date),
            escape_json(&to_date),
        ))
    }

    /// Generate the actual hledger journal file.
    fn generate_report(format: String, params: String) -> Result<Vec<u8>, String> {
        if format != "hledger" && format != "text" {
            return Err(format!("Unsupported format: {format}. Use 'hledger' or 'text'."));
        }

        logging::info("Generating hledger journal file");

        let base_currency = plugin_storage::get("base_currency")
            .map_err(|e| format!("Storage error: {e:?}"))?
            .unwrap_or_else(|| "EUR".to_string());

        let (from_date, to_date) = parse_date_range(&params)?;

        let accounts = ledger_read::list_accounts()
            .map_err(|e| format!("Failed to list accounts: {e:?}"))?;

        let mut transactions = ledger_read::query_transactions(&QueryParams {
            limit: 10000,
            offset: 0,
            account_filter: String::new(),
            from_date: from_date.clone(),
            to_date: to_date.clone(),
        })
        .map_err(|e| format!("Failed to query transactions: {e:?}"))?;

        transactions.sort_by(|a, b| a.date.cmp(&b.date));

        let mut output = String::new();

        // Header comment
        output.push_str("; Generated by dledger - hledger Export Plugin\n");
        output.push_str(&format!("; Period: {} to {}\n\n", from_date, to_date));

        // Account declarations
        for account in &accounts {
            if !account.is_postable {
                continue;
            }
            let hl_name = to_hledger_account(&account.full_name, &account.account_type);
            output.push_str(&format!("account {}\n", hl_name));
        }
        output.push('\n');

        // Commodity declarations for currencies we encounter
        let mut seen_currencies: Vec<String> = Vec::new();
        for tx in &transactions {
            for posting in &tx.postings {
                if !seen_currencies.contains(&posting.amount.currency) {
                    seen_currencies.push(posting.amount.currency.clone());
                }
            }
        }
        for currency in &seen_currencies {
            output.push_str(&format!("commodity {}\n", currency));
        }
        if !seen_currencies.is_empty() {
            output.push('\n');
        }

        // Price directives from exchange rates
        let crypto_currencies = find_crypto_currencies(&accounts, &base_currency);
        let dates = collect_unique_dates(&transactions);
        for crypto in &crypto_currencies {
            for date in &dates {
                if let Ok(Some(rate)) =
                    ledger_read::get_exchange_rate(crypto, &base_currency, date)
                {
                    output.push_str(&format!(
                        "P {} {} {} {}\n",
                        date, crypto, rate, base_currency
                    ));
                }
            }
        }
        if !crypto_currencies.is_empty() && !dates.is_empty() {
            output.push('\n');
        }

        // Transaction entries
        for tx in &transactions {
            // Header: date description
            output.push_str(&format!(
                "{} {}\n",
                tx.date,
                escape_hledger_description(&tx.description)
            ));

            // Metadata as comments
            for (key, value) in &tx.metadata {
                output.push_str(&format!("    ; {}:{}\n", key, value));
            }

            // Postings
            for posting in &tx.postings {
                let account_name = find_account_name(&accounts, &posting.account);
                let hl_account = to_hledger_account(
                    &account_name,
                    &find_account_type(&accounts, &posting.account),
                );

                // Format: "    account_name  amount currency"
                // Right-align amount for readability
                let amount_str = format!("{} {}", posting.amount.amount, posting.amount.currency);
                let padding = if hl_account.len() < 40 {
                    " ".repeat(40 - hl_account.len())
                } else {
                    "  ".to_string()
                };
                output.push_str(&format!(
                    "    {}{}{}\n",
                    hl_account, padding, amount_str
                ));
            }
            output.push('\n');
        }

        logging::info(&format!(
            "hledger export: {} accounts, {} transactions",
            accounts.len(),
            transactions.len()
        ));

        Ok(output.into_bytes())
    }
}

export!(ExportHledger);

// --- Helpers ---

fn parse_date_range(params: &str) -> Result<(String, String), String> {
    let from = extract_json_string(params, "from_date").unwrap_or_else(|| "2000-01-01".into());
    let to = extract_json_string(params, "to_date").unwrap_or_else(|| "2099-12-31".into());
    Ok((from, to))
}

/// Map dledger account type to hledger convention.
/// hledger uses the same five roots: assets, liabilities, equity, revenues, expenses
/// but also supports any top-level name. We use capitalized roots for consistency.
fn to_hledger_account(full_name: &str, account_type: &str) -> String {
    let parts: Vec<&str> = full_name.split(':').collect();
    if parts.is_empty() {
        return full_name.to_string();
    }

    let hl_root = match account_type {
        "asset" => "assets",
        "liability" => "liabilities",
        "equity" => "equity",
        "revenue" => "revenues",
        "expense" => "expenses",
        _ => parts[0],
    };

    if parts.len() <= 1 {
        return hl_root.to_string();
    }

    let rest: Vec<String> = parts[1..].iter().map(|p| p.to_lowercase()).collect();
    format!("{}:{}", hl_root, rest.join(":"))
}

fn find_account_name(accounts: &[AccountInfo], id: &str) -> String {
    accounts
        .iter()
        .find(|a| a.id == id)
        .map(|a| a.full_name.clone())
        .unwrap_or_else(|| id.to_string())
}

fn find_account_type(accounts: &[AccountInfo], id: &str) -> String {
    accounts
        .iter()
        .find(|a| a.id == id)
        .map(|a| a.account_type.clone())
        .unwrap_or_else(|| "asset".to_string())
}

fn find_crypto_currencies(accounts: &[AccountInfo], base_currency: &str) -> Vec<String> {
    let mut currencies = Vec::new();
    for account in accounts {
        let parts: Vec<&str> = account.full_name.split(':').collect();
        if let Some(last) = parts.last() {
            let currency = last.to_string();
            if currency != base_currency
                && currency.len() <= 5
                && currency.chars().all(|c| c.is_ascii_uppercase())
                && !currencies.contains(&currency)
            {
                currencies.push(currency);
            }
        }
    }
    currencies
}

fn collect_unique_dates(transactions: &[Transaction]) -> Vec<String> {
    let mut dates = Vec::new();
    for tx in transactions {
        if !dates.contains(&tx.date) {
            dates.push(tx.date.clone());
        }
    }
    dates
}

fn escape_hledger_description(s: &str) -> String {
    // hledger descriptions don't need quoting unless they contain special chars
    // Just escape any newlines
    s.replace('\n', " ").replace('\r', "")
}

fn escape_json(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

// --- JSON helpers ---

fn extract_json_string(json: &str, key: &str) -> Option<String> {
    let pattern = format!("\"{}\"", key);
    let idx = json.find(&pattern)?;
    let after_key = &json[idx + pattern.len()..];
    let after_colon = after_key.trim_start().strip_prefix(':')?.trim_start();
    if after_colon.starts_with('"') {
        let content = &after_colon[1..];
        let end = find_unescaped_quote(content)?;
        Some(content[..end].to_string())
    } else {
        None
    }
}

fn find_unescaped_quote(s: &str) -> Option<usize> {
    let mut prev = '\0';
    for (i, c) in s.char_indices() {
        if c == '"' && prev != '\\' {
            return Some(i);
        }
        prev = c;
    }
    None
}
