wit_bindgen::generate!({
    world: "handler",
    path: "../../wit",
});

use dledger::plugin::ledger_read;
use dledger::plugin::logging;
use dledger::plugin::plugin_storage;
use dledger::plugin::types::*;

struct ExportBeancount;

impl exports::dledger::plugin::metadata::Guest for ExportBeancount {
    fn get_metadata() -> PluginMetadata {
        PluginMetadata {
            name: "Beancount Export".to_string(),
            version: "0.1.0".to_string(),
            description: "Export ledger to Beancount format".to_string(),
            author: "dledger".to_string(),
        }
    }
}

impl exports::dledger::plugin::handler_ops::Guest for ExportBeancount {
    fn config_schema() -> Vec<ConfigField> {
        vec![ConfigField {
            key: "base_currency".into(),
            label: "Operating Currency".into(),
            field_type: "select".into(),
            required: true,
            default_value: "EUR".into(),
            description: "Operating currency for the beancount file".into(),
            options: "EUR,USD,GBP".into(),
        }]
    }

    fn configure(config: Vec<(String, String)>) -> Result<(), String> {
        for (key, value) in &config {
            plugin_storage::set(key, value)
                .map_err(|e| format!("Storage error: {e:?}"))?;
        }
        Ok(())
    }

    /// Process: return JSON summary of what would be exported.
    fn process(params: String) -> Result<String, String> {
        logging::info("Generating Beancount export");

        let (from_date, to_date) = parse_date_range(&params)?;

        let accounts = ledger_read::list_accounts()
            .map_err(|e| format!("Failed to list accounts: {e:?}"))?;

        let mut transactions = ledger_read::query_transactions(&QueryParams {
            limit: 10000,
            offset: 0,
            account_filter: String::new(),
            from_date: from_date.clone(),
            to_date: to_date.clone(),
        })
        .map_err(|e| format!("Failed to query transactions: {e:?}"))?;

        transactions.sort_by(|a, b| a.date.cmp(&b.date));

        Ok(format!(
            "{{\"format\":\"beancount\",\"accounts\":{},\"transactions\":{},\"from_date\":\"{}\",\"to_date\":\"{}\"}}",
            accounts.len(),
            transactions.len(),
            escape_json(&from_date),
            escape_json(&to_date),
        ))
    }

    /// Generate the actual beancount file.
    fn generate_report(format: String, params: String) -> Result<Vec<u8>, String> {
        if format != "beancount" && format != "text" {
            return Err(format!("Unsupported format: {format}. Use 'beancount' or 'text'."));
        }

        logging::info("Generating Beancount file");

        let base_currency = plugin_storage::get("base_currency")
            .map_err(|e| format!("Storage error: {e:?}"))?
            .unwrap_or_else(|| "EUR".to_string());

        let (from_date, to_date) = parse_date_range(&params)?;

        let accounts = ledger_read::list_accounts()
            .map_err(|e| format!("Failed to list accounts: {e:?}"))?;

        let mut transactions = ledger_read::query_transactions(&QueryParams {
            limit: 10000,
            offset: 0,
            account_filter: String::new(),
            from_date: from_date.clone(),
            to_date: to_date.clone(),
        })
        .map_err(|e| format!("Failed to query transactions: {e:?}"))?;

        transactions.sort_by(|a, b| a.date.cmp(&b.date));

        let mut output = String::new();

        // Header
        output.push_str(";; Generated by dledger - Beancount Export Plugin\n");
        output.push_str(&format!(";; Period: {} to {}\n\n", from_date, to_date));

        // Operating currency option
        output.push_str(&format!("option \"operating_currency\" \"{}\"\n\n", base_currency));

        // Account open directives
        // Use the earliest transaction date or a default
        let open_date = transactions
            .first()
            .map(|t| t.date.as_str())
            .unwrap_or("2020-01-01");

        for account in &accounts {
            if !account.is_postable {
                continue;
            }
            let bc_name = to_beancount_account(&account.full_name, &account.account_type);
            output.push_str(&format!("{} open {}\n", open_date, bc_name));
        }
        output.push('\n');

        // Transaction directives
        for tx in &transactions {
            // Transaction header: date * "description"
            output.push_str(&format!(
                "{} * \"{}\"\n",
                tx.date,
                escape_beancount_string(&tx.description)
            ));

            // Metadata
            for (key, value) in &tx.metadata {
                output.push_str(&format!("  {}: \"{}\"\n", key, escape_beancount_string(value)));
            }

            // Postings
            for posting in &tx.postings {
                let account_name = find_account_name(&accounts, &posting.account);
                let bc_account = to_beancount_account(
                    &account_name,
                    &find_account_type(&accounts, &posting.account),
                );
                let amount = &posting.amount.amount;
                let currency = &posting.amount.currency;

                output.push_str(&format!(
                    "  {} {} {}\n",
                    bc_account, amount, currency
                ));
            }
            output.push('\n');
        }

        // Price directives from exchange rates
        // Query a few common crypto currencies for price data
        let crypto_currencies = find_crypto_currencies(&accounts, &base_currency);
        for crypto in &crypto_currencies {
            // Try to get rates for dates in our transaction range
            let dates = collect_unique_dates(&transactions);
            for date in &dates {
                if let Ok(Some(rate)) =
                    ledger_read::get_exchange_rate(crypto, &base_currency, date)
                {
                    output.push_str(&format!(
                        "{} price {} {} {}\n",
                        date, crypto, rate, base_currency
                    ));
                }
            }
        }

        logging::info(&format!(
            "Beancount export: {} accounts, {} transactions",
            accounts.len(),
            transactions.len()
        ));

        Ok(output.into_bytes())
    }
}

export!(ExportBeancount);

// --- Helpers ---

fn parse_date_range(params: &str) -> Result<(String, String), String> {
    let from = extract_json_string(params, "from_date").unwrap_or_else(|| "2000-01-01".into());
    let to = extract_json_string(params, "to_date").unwrap_or_else(|| "2099-12-31".into());
    Ok((from, to))
}

/// Map dledger account type to beancount root.
/// Beancount requires: Assets, Liabilities, Equity, Income, Expenses
fn to_beancount_account(full_name: &str, account_type: &str) -> String {
    let parts: Vec<&str> = full_name.split(':').collect();
    if parts.is_empty() {
        return full_name.to_string();
    }

    // Map the root to beancount convention
    let bc_root = match account_type {
        "asset" => "Assets",
        "liability" => "Liabilities",
        "equity" => "Equity",
        "revenue" => "Income",
        "expense" => "Expenses",
        _ => parts[0],
    };

    if parts.len() <= 1 {
        return bc_root.to_string();
    }

    // Replace the first segment with the beancount root
    let rest: Vec<&str> = parts[1..].to_vec();
    format!("{}:{}", bc_root, rest.join(":"))
}

fn find_account_name(accounts: &[AccountInfo], id: &str) -> String {
    accounts
        .iter()
        .find(|a| a.id == id)
        .map(|a| a.full_name.clone())
        .unwrap_or_else(|| id.to_string())
}

fn find_account_type(accounts: &[AccountInfo], id: &str) -> String {
    accounts
        .iter()
        .find(|a| a.id == id)
        .map(|a| a.account_type.clone())
        .unwrap_or_else(|| "asset".to_string())
}

fn find_crypto_currencies(accounts: &[AccountInfo], base_currency: &str) -> Vec<String> {
    let mut currencies = Vec::new();
    for account in accounts {
        // Extract currency from account names like "Assets:Crypto:BTC" or "Assets:Exchange:Kraken:ETH"
        let parts: Vec<&str> = account.full_name.split(':').collect();
        if let Some(last) = parts.last() {
            let currency = last.to_string();
            if currency != base_currency
                && currency.len() <= 5
                && currency.chars().all(|c| c.is_ascii_uppercase())
                && !currencies.contains(&currency)
            {
                currencies.push(currency);
            }
        }
    }
    currencies
}

fn collect_unique_dates(transactions: &[Transaction]) -> Vec<String> {
    let mut dates = Vec::new();
    for tx in transactions {
        if !dates.contains(&tx.date) {
            dates.push(tx.date.clone());
        }
    }
    dates
}

fn escape_beancount_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_json(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

// --- JSON helpers ---

fn extract_json_string(json: &str, key: &str) -> Option<String> {
    let pattern = format!("\"{}\"", key);
    let idx = json.find(&pattern)?;
    let after_key = &json[idx + pattern.len()..];
    let after_colon = after_key.trim_start().strip_prefix(':')?.trim_start();
    if after_colon.starts_with('"') {
        let content = &after_colon[1..];
        let end = find_unescaped_quote(content)?;
        Some(content[..end].to_string())
    } else {
        None
    }
}

fn find_unescaped_quote(s: &str) -> Option<usize> {
    let mut prev = '\0';
    for (i, c) in s.char_indices() {
        if c == '"' && prev != '\\' {
            return Some(i);
        }
        prev = c;
    }
    None
}
